version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
      - "24678:24678"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    hostname: backend
